version: '3'
services:
  web:
    build: registration-web/
    ports:
      - 8090:8090
    links:
      - backend
    environment:
      VR_SERVER_ADDR: backend:8080
  backend:
    build: scheduler/
    ports:
      - "8888:8080"
    links:
      - dbsrv
  dbsrv:
    build: db/
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
